disabled_rules:
  - line_length
  - type_name

opt_in_rules:
  - empty_count
  - force_unwrapping

included:
  - Sources
  - MockingbirdTests
  - Examples

function_body_length:
  warning: 50
  error: 150