version: 2
jobs:
  build:
    macos:
      xcode: '10.2.1'
    steps:
      - checkout
      - run:
          name: Install Tools
          command: |
            brew install swiftlint
      - run:
          name: Generate Xcode project
          command: |
            swift package generate-xcodeproj
      - run:
          name: Build for release
          command: |
            swift build -c release
      - run:
          name: Run tests
          command: xcodebuild test -scheme Mockingbird-Package -project Mockingbird.xcodeproj -enableCodeCoverage YES
      - run:
          name: Send test coverage report
          command: bash <(curl -s https://codecov.io/bash)