name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Resolve dependencies
      run: swift resolve
    - name: Generate Xcode project
      run: swift package generate-xcodeproj
    - name: Run tests iOS
      run: xcodebuild -project 'Mockingbird.xcodeproj' -scheme 'Mockingbird-Package' -destination 'platform=iOS Simulator,name=iPhone 11' test | xcpretty
    - name: Run tests macOS
      run: xcodebuild -project 'Mockingbird.xcodeproj' -scheme 'Mockingbird-Package' -destination 'platform=macOS' test | xcpretty
    - name: Build framework
      run: swift build