name: SwiftLint

on:
  push:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Swiftlint
        uses: norio-nomura/action-swiftlint@3.0.1